// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO_-M-OMiZGzNKzS_GiQlcQiUqZoKZoZg',
    appId: '1:768784803209:web:a66875d9f36ca48d46ad58',
    messagingSenderId: '768784803209',
    projectId: 'chat-app-4399d',
    authDomain: 'chat-app-4399d.firebaseapp.com',
    storageBucket: 'chat-app-4399d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx0bKxK-caVxZ3FJqRRwft3GpQrE-tJes',
    appId: '1:768784803209:android:eded03dcec9f250946ad58',
    messagingSenderId: '768784803209',
    projectId: 'chat-app-4399d',
    storageBucket: 'chat-app-4399d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-B5nggygkwWa6c_wSSahOXYOjPbILHc8',
    appId: '1:768784803209:ios:5e69b1052c1bac1b46ad58',
    messagingSenderId: '768784803209',
    projectId: 'chat-app-4399d',
    storageBucket: 'chat-app-4399d.appspot.com',
    iosClientId: '768784803209-jn865nq4nsks64n0nd95pgoc4eqk0org.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-B5nggygkwWa6c_wSSahOXYOjPbILHc8',
    appId: '1:768784803209:ios:5e69b1052c1bac1b46ad58',
    messagingSenderId: '768784803209',
    projectId: 'chat-app-4399d',
    storageBucket: 'chat-app-4399d.appspot.com',
    iosClientId: '768784803209-jn865nq4nsks64n0nd95pgoc4eqk0org.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
